### ISSUE TITLE
Unable to Create an Actor

### ISSUE THREAD

**Issue by justinthejaguar** [gcsga/gcsga#105] opened 2023-12-24 21:52 UTC
Click Create Actor
Name character
Type Character
Click Create New Actor
![image](https://github.com/gcsga/gcsga/assets/38022481/d2262c76-916e-43f9-88df-bdbbf7cb9ff5)

Creating a Character (Legacy) populates the initial character and the legacy character with the 2.0 warning.

**Comment by rinickolous** [comment] 2024-01-01 00:07
Have you tried recreating this issue on a brand new world? I imagine this may be caused by corrupted or incorrectly set default resource tracker settings. Try resetting those to their default values and see if it resolves the issue.

**Comment by justinthejaguar** [comment] 2024-01-01 02:49
It was brand new. First time using the system. Happened within five minutes of opening the world. I can test again later if this doesn’t exist in new worlds for you.

**Comment by Ethanrat** [comment] 2024-01-07 18:21
I can confirm. I have the same issue on a clean install with no modules enabled. I check the resource tracker and it seems that in alpha 4 there are no defaults one on world creation. Resetting them fixes the issue.

**Comment by rinickolous** [comment] 2024-01-13 18:42
Fixed in latest update

**Closed by rinickolous** 2024-01-13 18:42 UTC
Labels: bug
